samvera/valkyrie

- app/controllers/concerns/model_controller_behavior.rb
- app/models/solr_document.rb
- app/persistence/valkyrie/persistence/fedora/query_service.rb
- app/persistence/valkyrie/persistence/memory/query_service.rb
- app/persistence/valkyrie/persistence/postgres/query_service.rb
- app/persistence/valkyrie/persistence/solr/query_service.rb
- app/persisters/appending_persister.rb
- app/processors/valkyrie/processors/append_processor.rb
- app/services/query_service.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- lib/valkyrie/specs/shared_specs/queries.rb
- script/benchmarker.rb
- spec/models/book_spec.rb
- spec/persisters/appending_persister_spec.rb
- spec/requests/books_spec.rb
If you name the param, you don't need to name it in the method name
also.
> Rename `find_by_id(id: id)` to `find_by(id: id)`

- app/persistence/valkyrie/persistence/fedora/persister.rb
- config/valkyrie.yml
This adds IDs instead of full ActiveFedora objects when persisting the members list. The benchmark difference can be seen below. Basically adding 100 children all at once goes from 14s to 2.4s.
https://gist.github.com/tpendragon/9d8c22a6d4cef66b27872955608ba8e3
> Speed up Fedora adapter.

- app/persistence/valkyrie/persistence/fedora/dynamic_klass.rb
- app/persistence/valkyrie/persistence/postgres/orm/resource.rb
- app/persistence/valkyrie/persistence/solr/mapper.rb
- app/persistence/valkyrie/persistence/solr/resource_factory.rb
- app/services/value_mapper.rb
- spec/persistence/valkyrie/persistence/solr/mapper_spec.rb
- spec/services/value_mapper_spec.rb
I was doing a lot of really similar work to convert values between states in a maintainable way in the various persisters. This makes them all use the same standard value mapper registration backend and contract.
> Standardize the Value Mapper pattern

- app/models/book.rb
- app/models/page.rb
- lib/valkyrie/active_model.rb
- lib/valkyrie/specs/shared_specs.rb
- lib/valkyrie/specs/shared_specs/model.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/models/book_spec.rb
- spec/models/page_spec.rb
- spec/persistence/valkyrie/persistence/solr/persister_spec.rb
Also renames Valkyrie::ActiveModel to Valkyrie::Model to be clearer.
> Add shared specs for Valkyrie::Model

- app/persistence/valkyrie/persistence/solr/mapper.rb
- app/persistence/valkyrie/persistence/solr/resource_factory.rb
- lib/valkyrie/specs/shared_specs/persister.rb
I wasn't expecting this, but both the Fedora persister and Postgres persister just worked.
> Add support for integer values

- lib/valkyrie/persistence/active_fedora/resource_factory.rb
There was a thought at one point this was necessary for SolrFaker to
work, but now everything just uses #attributes.
> Remove dead ActiveFedora::ResourceFactory code.

- .rubocop.yml
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
Mainly around using anonymous classes where possible instead of inline class declarations and follow-up undefinition of them.
A couple points where I used `let` for common constructions instead of repeated variable assignments.  I think this helps make the tests clearer for the part they are testing vs. what is setup.
> Spec cleanup

- valkyrie/lib/valkyrie/persistence.rb
- valkyrie/lib/valkyrie/persistence/buffered_persister.rb
- valkyrie/spec/valkyrie/persistence/buffered_persister_spec.rb
Allows for decorating on the ability to buffer a set of actions into a
memory persister. Really useful for doing a bunch of actions and then
indexing later.
Closes #98 
I wasn't going to make this a decorator originally, but seeing the exact same code split out amongst all the persisters seemed problematic. I didn't want to go down the road of a parent class yet, either.
> Add BufferedPersister.

- Gemfile.lock
Fixes #106 
Updating `database_cleaner` to 1.6.1 fixes the following deprecation warning:
`DEPRECATION WARNING: schema_migrations_table_name is deprecated and will be removed from Rails 5.2`
See: http://databasecleaner.github.io/2017/05/04/v1-6-0-is-out/
> Update to database_cleaner 1.6.1

- .gitignore
For those who might use `byebug` over `binding.pry` for whatever reason.
> add .byebug_history to the gitignore

- app/derivative_services/image_derivative_service.rb
- spec/derivative_services/image_derivative_service_spec.rb
Fixes #132 
Adds ImageDerivativeService support for the following formats:
```
image/gif
image/jpeg
image/png
image/tiff
```
Includes tests for valid and invalid mime_types for `ImageDerivativeService#valid?`
> Add multiple image format support for ImageDerivativeService

- app/file_characterization_services/tika_file_characterization_service.rb
- app/models/file_node.rb
- lib/valkyrie/persistence/active_fedora/orm/resource.rb
- spec/file_characterization_services/tika_file_characterization_service_spec.rb
- valkyrie/lib/valkyrie/file_characterization_service.rb
- valkyrie/spec/valkyrie/file_characterization_service_spec.rb
Refs: #163 
- Sets SHA256 hexdigest `checksum` attribute in `TikaFileCharacterizationService`
- Adds `checksum` property to `Valkyrie::Persistence::ActiveFedora::ORM::Schema`
> Add checksum to FileCharacterizationService

- valkyrie/lib/valkyrie/persistence/postgres/orm/resource.rb
- valkyrie/lib/valkyrie/persistence/solr/resource_factory.rb
Solr/Postgres were converting non-dates into dates because they'd make
it through DateTime.parse
> Use iso8601 method

- valkyrie/lib/valkyrie/persistence/solr/mapper.rb
Significantly improves suite time for our application. Generating
attributes takes a long time for Dry::Struct, it turns out.
> Caches object attributes in SolrMapper

- valkyrie/lib/valkyrie/persistence/postgres/orm/resource.rb
Provides a significant speedup by not capturing `method_missing` in the Figgy test suite.
> Don't run Date Checks on nil.

- config/blacklight.yml
- config/fedora.yml
- config/solr.yml
- lib/tasks/dev.rake
Fedora was being downloaded to temp space, which is deleted during
reboot, and the ports for the Fedora and two Solr instances weren't
changeable if local usage required it.
Fedora and Solr zip files are downloaded to the tmp directory where they
can remain until deleted. Also, each port for each Solr and Fedora
instance can be configured using an environment variable, should you
want to run Solr and Fedora independently on your local system.
> Update Fedora and Solr configurations

- valkyrie/lib/valkyrie/persistence/memory/query_service.rb
- valkyrie/lib/valkyrie/specs/shared_specs/queries.rb
Adding an additional object to the shared spec to show off the issue with the in memory adapter
Rescuing the error the in memory adapter throws when all objects do not respond to the property in find_inverse_refernces_by
> In memory adapter fails when all objects do not respond to property

- app/controllers/concerns/catalog.rb
- app/models/solr_document.rb
- app/services/query_service.rb
- app/views/catalog/_members_collection.html.erb
- spec/models/solr_document_spec.rb
- spec/views/catalog/_members_collection.html.erb_spec.rb
add query to solr document to allow for finding a collection's children
Displaying the children as the members of a collection instead of a separate partial
fixes #199
> Show all objects that are a member_of a collection

- app/models/solr_document.rb
- app/views/catalog/_admin_tools.html.erb
- app/views/catalog/_book_admin_list_items.html.erb
- spec/models/solr_document_spec.rb
- spec/views/catalog/_admin_tools.html.erb_spec.rb
Added a book? query to the solr document
Moved the book actions to a partial
Only display the book actions if the current resource is a book
This PR addresses the confusion I had with the Book buttons not working from the Collection page. 
Book Show page looks the same:
Collection Show page no longer has book actions:
> Only display book actions for books

- app/models/solr_document.rb
- spec/models/solr_document_spec.rb
Decorating the children allows them to be displayed nicely.  This was not needed when first was being called on the title in the solr document, but that has been removed.
View for master
View after PR
> Decorating children to display better

- valkyrie/lib/valkyrie/resource.rb
- valkyrie/lib/valkyrie/specs/shared_specs/resource.rb
Resolves #182 by extending Valkyrie resources with a method for generating human-readable type names
> Extends Resources to exposed human-readable type names

- README.md
- db/seeds.rb
When setting up a development server rake db:seed will create initial accounts for testing. Uses the emails from role_map.yml.
> Create initial user accounts

- valkyrie/.rubocop.yml
- valkyrie/lib/valkyrie/persistence/fedora.rb
- valkyrie/lib/valkyrie/persistence/fedora/metadata_adapter.rb
- valkyrie/lib/valkyrie/persistence/fedora/permissive_schema.rb
- valkyrie/lib/valkyrie/persistence/fedora/persister/model_converter.rb
- valkyrie/spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- valkyrie/spec/valkyrie/persistence/fedora/persister/model_converter_spec.rb
Valkyrie was making up predicates when persisting attributes to Fedora.
We needed a way to provide a predicate for each attribute in the
resource.
Fedora's metadata adapter will accept a hash as a schema and use any
defined predicate for a given term. If no predicate is defined, the
current default one will be used.
Custom schemas must be provided when initializing the metadata adapter
in config/initializers/valkyrie.rb.
> Custom predicates with Fedora resources, ref #198

- .rubocop.yml
- lib/valkyrie/persistence/active_fedora/orm/resource.rb
Prior to this commit, Rubocop identified a useless assignment. I believe
the intention of the prior code was to set the `file_size` property of
the Resource. However, as written, the assignment was "useless" because
it set a local variable `file_size` (instead of the property).
I believe the fix is to prepend `self.` to the `file_size` assignment,
thus setting the expected property instead of the local variable.
```ruby
def size=(size)
file_size = size
end
```
Related to d5528472f91d89617e64b1ef4185410a6be0b204
> Removing useless local variable assignment

- .rubocop.yml
The exception no longer appears necessary.
> Removing Rubocop exception

- valkyrie/lib/valkyrie/persistence/fedora/metadata_adapter.rb
- valkyrie/lib/valkyrie/persistence/memory/metadata_adapter.rb
- valkyrie/lib/valkyrie/persistence/postgres/metadata_adapter.rb
- valkyrie/lib/valkyrie/persistence/solr/metadata_adapter.rb
- valkyrie/lib/valkyrie/specs/shared_specs/metadata_adapter.rb
Registration is at the instance level of the query service, but it was
generating a new one every time. This preserves custom queries.
> Fix query service caching for custom queries.

- valkyrie/lib/valkyrie/specs/shared_specs/queries.rb
This PR allows for Hyrax::Queries to be tested using the shared spec.  Also included is testing that find_members responds to the recently added optional model keyword.
> Allow for query_service to be defined and provided outside of the adapter

- valkyrie/lib/valkyrie/types.rb
- valkyrie/spec/valkyrie/types_spec.rb
Otherwise using the concat (or `<<` operator) on an instance, causes the schema to be modified.
> Array defaults are not modifiable

- valkyrie/lib/valkyrie/persistence/solr.rb
- valkyrie/lib/valkyrie/persistence/solr/composite_indexer.rb
- valkyrie/spec/valkyrie/persistence/solr/composite_indexer_spec.rb
Added the CompositeIndexer class from Figgy:
https://github.com/pulibrary/figgy/blob/master/app/indexers/composite_indexer.rb
Namespaced under persistence/solr
Plus test which checks that an embedded indexer works. I don't think this needs a shared_spec given it's testing solr indexing.
> add composite_indexer

- valkyrie/lib/valkyrie/persistence/fedora/query_service.rb
- valkyrie/lib/valkyrie/persistence/memory/query_service.rb
- valkyrie/lib/valkyrie/specs/shared_specs/queries.rb
Without this check having a resource without a member_ids property in the cache causes `find_parents` and other queries to throw a `NoMethodError`.
I think the second shared spec which I added (to cover the original issue) doesn't make a whole lot of sense but it correctly fails the memory adapter as it currently is.
> Check that the resource responds to member_ids before calling it

- valkyrie/lib/valkyrie/change_set.rb
- valkyrie/spec/valkyrie/change_set_spec.rb
The rails tag helper interprets `required=>nil` as `"required"=>""`
which is a required field.
> ChangeSet#multiple? returns false rather than nil.

- valkyrie/lib/valkyrie/resource.rb
- valkyrie/spec/valkyrie/resource_spec.rb
Otherwise controllers or controller tests must cast `params[:id].to_s`
The equivalent ActiveModel behavior is here:
https://github.com/rails/rails/blob/47eadb68bfcae1641b019e07e051aa39420685fb/activemodel/lib/active_model/conversion.rb#L80-L84
> to_param must return a string

- lib/valkyrie/persistence/solr/model_converter.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
`#created_at` reports that it returns a String but before this change it was often returning a Time because `resource_attribute[:created_at]` is generally a Time and it wasn't being coerced.  This was leading to oddness in Hyrax when using the `ModelConverter` to create `SolrDocument`s from a `Valkyrie::Resource` for tests.
> Ensure that created_at is actually a String

- lib/valkyrie/persistence/solr/repository.rb
This will let downstream tests override the autocommit without the overhead of changing the adapter's public interface.
> Move solr commit param to class constant

- db/migrate/20161007101725_create_orm_resources.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/postgres/resource_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
This adds support for optionally using a string for the id field instead of a uuid so that an application can use things like NOIDs. Changes:
- Added support for specifying an env at migration time to change the id type to string. It will still use uuid_generate_v4 for the default if no id is provided, but this relieves the constraint of it being a uuid. This is required so that we can run all specs for each type to prevent regression of support for both types. Example: `VALKYRIE_ID_TYPE=string bundle exec rake db:drop db:create db:migrate && bundle exec rspec spec`
- Changed the pg queries to read the type for the id field to perform the correct casting
- Added a spec to ensure all adapters allow writing a custom id on persist
- Deep in the internals of active record's connection …
> Support string type for primary key

- lib/valkyrie/resource.rb
- spec/valkyrie/resource_spec.rb
This allows us to get the inherited attributes of all parent classes instead of just dry-struct
fixes #329
> Calling super instead of a specific class

- lib/valkyrie/metadata_adapter.rb
- spec/valkyrie/metadata_adapter_spec.rb
Prior to this commit, the following was used to retrieve a `persister`
or a `query_service`:
```ruby
Valkyrie::MetadataAdapter.find(:indexing_persister).query_service
```
With the following change, we can now use:
```ruby
Valkyrie::MetadataAdapter.find_query_service_for(:indexing_persister)
```
In removing the method chaining, any upstream dependency inversion
becomes easier to implement and utilize.
Responding to https://github.com/samvera/hyrax/pull/2358
https://github.com/samvera/hyrax/pull/2358/files/b50c05a38c1dbe511fa46016db50b68373142014#diff-21e2261d854a7e8fb6ea96ec414bc7d8R47
> Exposing methods to reduce upstream chaining

- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/persistence/memory/persister.rb
- lib/valkyrie/persistence/postgres/orm_converter.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- lib/valkyrie/specs/shared_specs/queries.rb
- spec/valkyrie/resource_spec.rb
Fixes a loop when adding `ActiveModel::Conversion` because conversion
defines `to_param` in terms of `persisted?`, which Valkyrie previously
defined in terms of `to_param`
Fixes #338
> Track persistence independent of presence of an identifier

- lib/valkyrie/persistence/solr/orm_converter.rb
Because the message on a key error is more useful for debugging.
Compare:
```
KeyError:
key not found: "internal_resource_ssim"
```
to
```
NoMethodError:
undefined method `first' for nil:NilClass
```
> Prefer KeyError to nil pointer error

- lib/valkyrie/persistence/memory/persister.rb
- lib/valkyrie/specs/shared_specs/persister.rb
Fixes `spec/models/hyrax/permission_template_spec.rb:16` in hyrax's valkyrie-6 branch.
> Creating resources with id sets created_at and new_record

- lib/valkyrie/storage_adapter.rb
- spec/valkyrie/storage_adapter_spec.rb
131dad8d6f02c06dca712bec5e15d7e8d24e93e9
83b41768d82b75366f527dca32ca23becdf8f976
I'm assuming that failure to find an adapter should raise an exception
instead of returning a `nil` object.
This behavior mirrors the Valkyrie::MetadataAdapter.find behavior.
> Working on valkyrie understanding part 2

- db/migrate/20180212092225_create_updated_at_index.rb
My use case for this index is to support fixity checks. Because reaching into the (nested) metadata for a last_run_fixy_check value was not performant, we're running fixity on update and at the same time a job that checks the file set which was least-recently updated. This index will support that job.
Can of course be used for other things, like finding recently-updated models :)
> Add index for updated_at to orm_resources

- lib/valkyrie/indexers/access_controls_indexer.rb
- spec/valkyrie/indexers/access_controls_indexer_spec.rb
Closes #325
Also fixes bug wherein edit group was set twice and individual set 0
times; each now set once.
> Add test coverage for access_controls_indexer

- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
Fixes edge cases like hashes or Times which should be cast to arrays,
but not become an array of numbers.
Closes #321, closes #320
> Use Array.wrap for coercing arrays

- lib/valkyrie/change_set.rb
- spec/valkyrie/change_set_spec.rb
This was done to include validators_on for better integration with simple form.
> Adding Reform::Form::ModelReflections to ChangeSet class fixes #327

- lib/valkyrie/specs/shared_specs/persister.rb
Unfortunately postgres and solr do not support most of the RDF Types, and fedora also does not support some.
fixes #209 
Here is an example of the failure on the test when it is not marked pending:
1) Valkyrie::Persistence::Postgres::Persister behaves like a Valkyrie::Persister can handle Time RDF properties
Failure/Error: expect(reloaded.title).to contain_exactly RDF::Literal.new(time)
expected collection contained:  [#<RDF::Literal::Time:0x3fc2f815d664("09:17:22-05:00"^^<http://www.w3.org/2001/XMLSchema#time>)>]
actual collection contained:    [#<RDF::Literal:0x3fc2f6942098("09:17:22-05:00")>]
the missing elements were:      [#<RDF::Literal::Time:0x3fc2f815d664("09:17:22-05:00"^^<http://www.w3.org/2001/XMLSchema#time>)>]
the extra elements were: …
> Adding test for RDF types

- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
Fixes #313 Stops pairtree generation upon encountering a slash (or dash, as before). Encode the id when converting to or from a URI.
Also changes the spec's adapter base_path to match documentation examples, avoiding extraneous slashes in URIs.
> Support ids containing slashes.

- valkyrie.gemspec
The interface has changed substantially in 0.13.0 and Valkyrie isn't set
up for it yet - will require many deprecation warnings and changes.
> Lock dry-types to < 0.13.0

- .circleci/config.yml
- valkyrie.gemspec
Bundle check will return true even if outdated gems are the only ones
available.
The nightly build should have been failing and wasn't because of this.
> Always bundle, don't just check.

- valkyrie.gemspec
fixes #440
see https://github.com/rails/rails/blob/v5.1.6/activerecord/CHANGELOG.md#rails-515-february-14-2018
> Loosen pg dependency; rails supports 1.0 in 5.1.5

- lib/valkyrie/resource.rb
- spec/valkyrie/resource_spec.rb
Fixes #452 
Adds a property to resource that will enable optimistic locking for each persister.
> Add enable_optimistic_locking on Valkyrie::Resource

- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/specs/shared_specs/locking_query.rb
- spec/valkyrie/persistence/solr/query_service_spec.rb
We'll deal with the fact that these aren't coming through from the persister in a forthcoming (persister-focused) PR
connected to #286
connected to #453
> Add optimistic_lock_token to valkyrie resources on query

- lib/valkyrie/persistence.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/repository.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/locking_persister.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
- spec/valkyrie/resource_spec.rb
Fixes #453 
Adds the optimistic locking attribute to the Solr persister so that `_version_` is added and return from update requests.
> Add optimistic locking attribute to Solr persister

- spec/valkyrie/types_spec.rb
It's been deprecated. `member` still works for now, but when we
upgrade...
Closes #413
> Use `of` instead of `member`.

- lib/valkyrie/resource.rb
- spec/valkyrie/resource_spec.rb
https://github.com/samvera-labs/valkyrie/pull/500 broke inheritance for upstream applications, resulting in all
`internal_resource` values being equal to ['Resource']. This fixes that.
> Inherited classes now properly re-scheme attrs.

- lib/valkyrie/persistence/postgres/metadata_adapter.rb
- spec/valkyrie/persistence/postgres/metadata_adapter_spec.rb
Figgy was having trouble using the previous access method, and this
delegates figuring out the environment to ActiveRecord which seems more
appropriate anyways.
> Use #connection_config to generate postgres ID

- lib/valkyrie/resource.rb
- spec/valkyrie/resource_spec.rb
This fixes a breaking change introduced by #500 and sends a deprecation
warning to warn users that it won't allow overriding the type in the
future.
> Allow users to override built in attributes.

- db/migrate/20180802220739_add_optimistic_locking_to_orm_resources.rb
- lib/valkyrie/persistence/postgres/metadata_adapter.rb
- lib/valkyrie/persistence/postgres/orm_converter.rb
- lib/valkyrie/persistence/postgres/persister.rb
- lib/valkyrie/persistence/postgres/resource_converter.rb
- lib/valkyrie/persistence/postgres/resource_factory.rb
- lib/valkyrie/resource.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
- spec/valkyrie/persistence/postgres/query_service_spec.rb
- spec/valkyrie/resource_spec.rb
Closes #456.
Closes #459.
This is ready for review, but it needs to be rebased on master after #510 is merged.
I've confirmed that this PR works on Figgy -without- running the database migration.
> Optimistic Locking for Postgres

- .rubocop_todo.yml
- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- spec/valkyrie/persistence/fedora/permissive_schema_spec.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
> Add optimistic locking to Fedora

- README.md
Fixes #491 
See also https://github.com/samvera-labs/valkyrie/wiki/Using-Types#ordering-values
> Adding ordering to attribute docs in README

- lib/valkyrie/persistence/composite_persister.rb
- spec/valkyrie/persistence/composite_persister_spec.rb
So it is saved when the next persister looks for it. This could only be
tested with some non-memory adapters.
> Change composite persister to duplicate cached resource

- lib/valkyrie/storage/fedora.rb
- spec/valkyrie/storage/fedora_spec.rb
Fixes #315 
Pass an Ldp::Client to the storage adapter, just like we do with the metadata adapter.
Not sure if `IOProxy` is still needed. We also aren't getting any metadata back from `fcr:metadata` because I think `AF::File` wrapped that. We could think about our own file object to do that if needed.
> Removes ActiveFedora from the storage persister

- .rubocop_todo.yml
- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/persistence/fedora/persister/resource_factory.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
Adding a second lock token for Fedora to hold the system-managed fedora:lastModified value, for use with the `If-Unmodified-Since` header.
Fixes #522
Alternative to #531
> Using Fedora's If-Unmodified-Since header to prevent clobbering another client's writes

- README.md
- lib/valkyrie/persistence/fedora/list_node.rb
- spec/spec_helper.rb
Fixes #549
ActiveFedora is no longer required for the test suite and should not be
referenced in the documentation.
Note: There is a briefly delay during one of the tests when ActiveFedora
is first called, in order to test the deprecation warning.
> Remove ActiveFedora from the documentation and test setup

- spec/valkyrie/id_spec.rb
The spec was failing sometimes because RDF::URI was comparing against it
and calling `to_uri` which was caching what the port was in AF.
> Change spec instead of port for Valkyrie::ID.

- lib/valkyrie/storage/fedora.rb
Test coverage showed this code wasn't being used — turns out the `response` method was already catching the error.
> Removing unused error handling (error is caught somewhere else)

- lib/valkyrie/specs/shared_specs/persister.rb
We have a bug that relates to precision in date storage. Ticket
separately.
> Reduce precision of Time.now in shared spec for ordered dates

- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/persistence/postgres/orm/resource.rb
- lib/valkyrie/persistence/postgres/resource_converter.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
AR was being helpful and still optimistically locking in some cases, even if the resource had it disabled.
> Postgres - don't lock if resource has it disabled

- lib/valkyrie/persistence/solr/repository.rb
- spec/spec_helper.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
- valkyrie.gemspec
This resolves a bug observed via figgy, wherein a timeout from solr sent
back a response with no status and resulted in
`NoMethodError: undefined method `[]' for nil:NilClass`
on `if exception.response[:status] == 409`
> Fix solr persister to pass through exceptions on timeout

- .rubocop_todo.yml
- lib/valkyrie.rb
- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/metadata_adapter.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/metadata_adapter.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/metadata_adapter.rb
- lib/valkyrie/persistence/solr/queries/find_members_query.rb
- lib/valkyrie/persistence/solr/queries/find_ordered_references_query.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- spec/valkyrie/persistence/memory/metadata_adapter_spec.rb
- spec/valkyrie/persistence/postgres/metadata_adapter_spec.rb
- spec/valkyrie/persistence/solr/metadata_adapter_spec.rb
This is based on the work started by @escowles. I reorganised the specs so that they are among all the method descriptions rather than in one block at the end.
I've also fixed the adapters to pass the tests except for Fedora which fails the find_inverse_references_by tests when the property is ordered. This is the case where it just didn't work at all to begin with. It's because there's the whole proxy list structure and the current implementation doesn't account for that.
I tried this which I thought should work but won't because the proxies seem to store the proxy_for as a literal rather than a reference to the object. So content_with_inbound doesn't return even the proxy objects.
```ruby
def find_inverse_references_by(resource:, property:)
ensure_persisted(resource)
content = …
```
> Adapter consistency

- lib/valkyrie/specs/shared_specs/file.rb
- spec/valkyrie/storage_adapter/file_spec.rb
- spec/valkyrie/storage_adapter/stream_file_spec.rb
Officially adds `disk_path` to the public API.
Closes #610.
> Add disk_path to shared specs.

- .docker-stack/valkyrie-development/docker-compose.yml
- .docker-stack/valkyrie-test/docker-compose.yml
- tasks/dev.rake
The extra solr index was from when the Fedora adapter used ActiveFedora.
Credit goes to @dgcliff for noticing this!
> Remove extraneous solr setup.

- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/resource.rb
- lib/valkyrie/types.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
- spec/valkyrie/resource_spec.rb
- spec/valkyrie/types_spec.rb
These are deprecations we've discovered are necessary via upgrading to the latest version of dry-struct.
> Implement Deprecations in Preparation for Valkyrie 2.0

- .docker-stack/valkyrie-development/docker-compose.yml
- .docker-stack/valkyrie-test/docker-compose.yml
- README.md
- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/storage/fedora.rb
- spec/support/fedora_helper.rb
- spec/support/wipe_raw_fedora_adapter.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- spec/valkyrie/persistence/fedora/persister/model_converter_spec.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
- spec/valkyrie/persistence/fedora/query_service_spec.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
- spec/valkyrie/storage/fedora_spec.rb
- tasks/dev.rake
Adds Fedora 5 compatibility, via a new `fedora_version` parameter to the Fedora metadata and storage adapters.
> Fedora 5 support

- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
This handles blank-string casting from HTML forms.
Closes #605.
> Add Valkyrie::Types::Params::ID

- lib/valkyrie/specs/shared_specs/resource.rb
This was causing issues with shared specs because the :string_property attribute was still defined on the sample resource.
Fixes #641
> Remove :string_property from the test resource

- lib/valkyrie/specs/shared_specs/queries.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
Other documentation might be good but this is a start.
Resolves #646.
> Use Set.of(ID) in spec models to model good modeling to ensure casting.

- lib/valkyrie/specs/shared_specs/resource.rb
Fixes #648 
It's not the most elegant solution, but it appears to eliminate the errors we're seeing in CHO when we run lots of unit tests with the Valkyrie::Resource share spec.
> Don't add test properties if they're already defined

- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/spec_helper.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
- valkyrie.gemspec
This also changes the Solr adapter to handle creating its own updated_at
too, but will be backwards compatible with previous assumptions of using
"timestamp."
Closes #639
> Enforce updated_at being set correctly.

- README.md
- lib/valkyrie.rb
- lib/valkyrie/persistence/postgres/orm_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/types.rb
- spec/valkyrie_spec.rb
Prior to this commit, there was an assumption that the constant used as
the source for sending to the persistence layer is the same as the
target used for reifying from the persistence layer.
With this commit, we have a crease for which we can, in upstream
implementations, create a different resolver strategy.
From revgum:
> It seems there's room for documenting the dependency and raising an
> appropriate exception for a circumstance with a dynamically generating
> a class.
>
> See https://github.com/samvera/hyrax/blob/5a2906ad69266245bd80c8528e35060a21aefde5/lib/hyrax/valkyrie/resource_factory.rb#L39 for the dynamic generation of the class.
>
> `internal_resource.constantize` fails, expectedly at : https://github.com/samvera-labs/valkyrie/blob/master/lib/valkyrie/persistence/postgres/orm_ …
> Adding configuration for resource_klass resolver

- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/queries/find_inverse_references_query.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
fixes #609
The only way to achieve this in the fedora query service is by retrieving the resource when the id is provided, due to the ordered property guarantee. This means we probably cannot deprecate the resource: parameter unless we want to be jerks to fedora users.
The concrete use case for this is #660
> Add id: param to find_inverse_references_by

- lib/valkyrie/specs/shared_specs/persister.rb
The persister shared specs depend on a `query_service` that isn't defined within the shared specs.  Existing valkyrie adapters define it with a `let()`.  This PR raises an error when it is not defined consistent with other dependent variables in to the shared specs.
> Query service must be set for persister shared specs

- lib/valkyrie/version.rb
RC2 accidentally removed a bunch of the actual 2.0 code because of some rebasing of a reverted merge.
> Valkyrie 2.0.0.RC3

- lib/valkyrie/specs/shared_specs.rb
- lib/valkyrie/specs/shared_specs/change_set_persister.rb
- lib/valkyrie/specs/shared_specs/queries.rb
- lib/valkyrie/specs/shared_specs/resource.rb
- lib/valkyrie/specs/shared_specs/solr_indexer.rb
- lib/valkyrie/specs/shared_specs/storage_adapter.rb
Sometimes ones like `Resource` were conflicting with constants defined
in the Valkyrie applications that used them, breaking specs.
> Namespace shared spec resources.

- .circleci/config.yml
- README.md
- spec/spec_helper.rb
- valkyrie.gemspec
It just slows down our PR process, especially when we require 100% coverage for PRs to be merged.
> Remove Coveralls.

- lib/valkyrie/persistence/fedora.rb
- lib/valkyrie/persistence/fedora/list_node.rb
- valkyrie.gemspec
It was only being used for a very small and very internal reason. It was
easy to remove, so why not do so?
> Remove ActiveTriples as a dependency.

- README.md
This also removes the Waffle badge (it's being removed) and changes the
YARD badge to point to the gem (this updates more regularly.)
> Switch README from samvera-labs to samvera

- lib/valkyrie/persistence/solr.rb
This require appears to just be in error. It was re-added to support a deprecation, which is now removed.
> Remove Solr adapter's dependency on Postgresql

- lib/valkyrie/specs/shared_specs/storage_adapter.rb
- lib/valkyrie/storage/disk.rb
- lib/valkyrie/storage/fedora.rb
- lib/valkyrie/storage/memory.rb
Ports the work introduced by @tpendragon to permit additional arguments for the Valkyrie::Storage adapter method #uploadts for the Valkyrie::Storage adapter method #upload
Resolves #705
> Permits additional arguments for the Valkyrie::Storage adapter method #upload

- lib/valkyrie/storage/fedora.rb
- spec/valkyrie/storage/fedora_spec.rb
Fixes: #736
The #id_to_uri method is only tested under Fedora 5.  There are no differences in how this method performs based on fedora version. 
By using the id_transformer without passing any additional information, the passed in transformer needs to handle connection and basepath.  This effectively means the connection and basepath provided when the storage adapter was created are ignored.
**OPTION 1:** Leave as is and let the caller handle the full translation (the code already in Hyrax does this)
**OPTION 2:** Make the id_transformer have signature (id, connection_prefix, basepath).  The transformer needs to know how to construct the first part of the path from these.
**OPTION 3:** Have the fedora storage adapter construct the first part of the path from connection_prefix and …
> add parameter to pass in custom id_transformer to upload

- lib/valkyrie/specs/shared_specs/resource.rb
Prevents polluting the attribute schema of a class which will be tested
in outside applications.
> Use a dynamic subclass for Resource shared specs.

- .docker-stack/valkyrie-development/docker-compose.yml
- .docker-stack/valkyrie-test/docker-compose.yml
Moving `fcrepo4` docker images out of the `nulib` namespace and into the `samvera` namespace
> Use samvera/fcrepo4 docker images instead of nulib/fcrepo4

- lib/valkyrie/resource.rb
- spec/valkyrie/resource_spec.rb
Fixes #760.
`Dry::Struct` sets attributes using the `.attributes` class method. Calls to the
individual `.attribute` configuration method pass through to there. In some
cases, it's desirable to setup many attributes at once, by directly calling
`.attributes`.
The various checks we add in `Valkyrie::Resource.attribute` are missed for users
who take advantage of this lowel level schema setup. This fixes one of those
cases, by ensuring valkyrie-style attribute setters get built for all
attributes, regardless of whether they were setup individually or as part of a
schema.
Several other fixes can be considered by moving `raise` and `:member_ids` type
casting down into this method as well.
> Define setters when building a Resource schema with `.attributes`

- lib/valkyrie/persistence/postgres/resource_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
Closes #767
We've been doing this in valkyrie-sequel the entire time and have had no
issues in Figgy. It's more performant, and there's no reason to do a
merge of the existing metadata.
> Don't merge postgres attributes, just overwrite them.

- lib/valkyrie/resource.rb
Push the `:member_ids` override down to `.attributes`.
Fixes #762.
I don't have a great idea about how to test for regressions, but this works as a proposed fix.
> Ensure `:member_ids` is ordered when using schema style attributes

- lib/valkyrie/persistence/fedora.rb
- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/storage/fedora.rb
Introduce `DEFAULT_FEDORA_VERSION` and set it to 5.
Closes #720.
> Use a DEFAULT_FEDORA_VERSION constant for the Fedora adapter

- lib/valkyrie/persistence/fedora/list_node.rb
Fixes #585 
After conversation with @tpendragon, we decided that `target_id` was fine and it was only `target_uri` that needed to change (since it doesn't always resolve to a URI)
> Rename ListNode#target_uri -> ListNode#target

- db/schema.rb
Fixes #773 
Directly removes the bookmarks, users, and searches tables from the db/schema.rb.  They are not used and their presence is confusing.
> Remove unused database tables.

- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/solr/persister.rb
- lib/valkyrie/persistence/solr/query_service.rb
Replaces yard doc for Solr QueryAdapter and Solr Persister methods with references
to Memory QueryAdapter and Memory Persister, respectively.
Refs #579
> Replaces duplicate yard doc with references

- spec/valkyrie/persistence/buffered_persister_spec.rb
Given that persister was named both as an let variable and yielded
variable, there is a possibility of shadowing. This commit removes
that from the specs.
> Removing shadowing of yielded variable

- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
We should use the existing example.com/example.org URLs for tests, not made-up URLs that might be registered.
> Use example.com instead of made-up URLs

- lib/valkyrie/storage_adapter.rb
- spec/valkyrie/storage_adapter_spec.rb
Raise an error when unable to find a StorageAdapter 
Fixes #683
> Fixes #683 - Raise an error when unable to find a StorageAdapter

- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
Fixes #791
Removes the check on the parent resource to determine if the property is ordered.  This was a bug as the property is expected to be defined on the child.  The shared specs were adjusted to create classes where the property is ordered in one child class, unordered in a second child class, and the property does not exist in the parent.
Fedora was the only adapter with the bug in how it found resources through the inverse relationship. Fedora stores ordered and unordered using a different pattern, so the find_inverse_reference_by method was modified to find children using both patterns.
@escowles @tpendragon This is ready for review.
> Allow property for find_inverse_reference_by to be ordered and unordered in related object

- spec/spec_helper.rb
Prior to this commit, it appeared that the specs ran in a sequential
order. Assuming they are running in the same order during each test,
this could mean that we have unknown temporal dependencies in our code.
Could we switch Valkyrie's specs to run in random order, thus helping
tease out if there exist temporal dependencies in our code.
_In running them randomly it appears to preserve meaningful
documentation format._
Closes #797
> Randomizing order of spec execution

- lib/valkyrie.rb
- lib/valkyrie/logging.rb
- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/solr/repository.rb
- spec/spec_helper.rb
- spec/valkyrie/logging_spec.rb
In gem development there are several considerations regarding logging.
1) The development on the gem directly, in particular specs
2) The downstream development that leverages the gem, both when specs
are running and when running the downstream processes in a development
environment.
3) The downstream behaviors that are called in production environments.
This patch provides the ability for developers to suppress logs.
Closes #796
> Adding ability to suppress valkyrie logging

- lib/valkyrie/persistence/fedora/persister.rb
I introduced an error in logic in commit c670eaa4eb252e048f97335e63b983731f35cbc7
Prior to c670eaa4eb252e048f97335e63b983731f35cbc7 was, in effect, the
following:
```ruby
Valkyrie.logger.error unless error.is_a?(::Ldp::NotFound)
```
However, with c670eaa4eb252e048f97335e63b983731f35cbc7 it logically
became:
```ruby
return unless error.is_a?(::Ldp::NotFound)
Valkyrie.logger.error
```
The end result is that there exists a lot more logging that is in error.
> Fixing logging error

- lib/valkyrie/persistence/memory/query_service.rb
Prior to this commit, the documentation for the class was disassociated
with the class. After this commit, the documentation (as rendered) will
be associated with the class.
> Tidying up documentation

- spec/valkyrie/types_spec.rb
Prior to this commit, the documentation read as follows:
```console
Valkyrie::Types
#<Dry::Types[Constructor<Nominal<Valkyrie::Persistence::OptimisticLockToken> fn=lib/valkyrie/types.rb:57>]>
casts from a string
```
With the change, we now get:
```console
Valkyrie::Types
Valkyrie::Types::OptimisticLockToken
casts from a string
```
I find this more legible and less surprising when reading the specs.
With the prior format, I'm left wondering "is there a stray puts call?"
I see the prior output as something "programmatic and as not clear as
documentation."
This attempts to tidy that up. However, I see this as something up for
discussion.
> Tidying up spec documentation output

- spec/spec_helper.rb
Prior to this commit, when I ran `rspec --seed 2053`, I would see logged
warnings. My suspicion is that that logger suppressions were getting
cleared.
After this commit, the suppression is redeclared as part of each run.
> Suppressing warning in more generalized case

- lib/valkyrie/resource.rb
In a sibling method, we use `self.class.schema.key(key.to_sym)`. Prior
to this commit, the changed method used `self.class.schema.key(key)`.
With the change, I'm adding symmetry to the `schema.key` lookup to align
expectations.
> Adding parity in schema.key lookup

- lib/valkyrie/persistence/composite_persister.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/valkyrie/resource_spec.rb
Prior to this commit, the logic for clearing the optimistic lock resided
outside the resource that code be locked. In addition, it used a `#send`
message that had intimate knowledge about attribute implementation.
This commit wraps that logic into a single method.
> Promote logic to method

- lib/valkyrie/id.rb
- spec/valkyrie/types_spec.rb
Fixes Issue #622 (seems to be tagging the release, see: https://github.com/samvera/valkyrie/issues/662)
Valkyrie::ID#eql? and == should return true when a string is compared with an equivalent Valkyrie::ID
Added test to verify this behavior. The following examples should work per the example:
```
[11] pry(main)> id = Valkyrie::ID.new('abc')
=> #<Valkyrie::ID:0x007fdee25d4760 @id="abc">
[12] pry(main)> id.eql?('abc')
=> true
[13] pry(main)> id == 'abc'
=> true
[14] pry(main)> id == 'def'
=> false
[15] pry(main)> id == Valkyrie::ID.new('abc')
=> true
```
Following tests should pass: `bundle exec rspec spec/valkyrie/types_spec.rb` should verify this behavior.
Note: I just submitted my Individual Contributors License Agreement to Samvera Legal so not sure how long it takes to verify.
> Fixes #622: Valkyrie ID should equal string equivalent of ID to string

- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
Valkyrie::Types::OrderedRelation in lib/valkyrie/types.rb
Co-authored-by: Greg Luis <gregorio.luisramirez@oregonstate.edu>
Co-authored-by: Linda Sato <lsato@uoregon.edu>
Co-authored-by: Henry Neels <foglaboratories@gmail.com>
fixes #651
> Adds aliases for Valkyrie::Types::Relation and

- lib/valkyrie/rdf_patches.rb
`RDF::JSON` exists in some contexts, e.g. after `require `linkeddata`. When it
does, this name fails to resolve. Using the anchor `::` ensures we look for
`JSON::LD` in the top level namespace.
Fixes #772
> Use `::` prefixed names for `JSON::LD` references

- valkyrie.gemspec
RSolr can't handle Faraday 1.0 yet. We should be able to loosen this
later.
> Lock Faraday to < 1.0.

- lib/valkyrie.rb
- lib/valkyrie/id.rb
- spec/valkyrie/types_spec.rb
This allows us to release without a major version, and we can deprecate
it later.
> Place new ID equality behind a config option.

- lib/valkyrie/id.rb
- spec/valkyrie/types_spec.rb
This makes the coverage always work. Thanks to @dgcliff
> Don't actually set config for ID equality.

- valkyrie.gemspec
older versions of rake have security vulnerabilities. since `rake` is
particularly stable, and it's just a development dependency, it seems safe to
leave it open ended.
this probably doesn't need an immediate release.
> allow open-ended rake support

- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/persistence/memory/persister.rb
- lib/valkyrie/persistence/shared/json_value_mapper.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
See #830. Valkyrie normalizes DateTime values to UTC to ensure consistency. This commit changes the method used from `.utc` to `.new_offset(0)`. The former returns a Time rather than a DateTime, which causes the type checking in the strict DateTime type to fail. The latter does the same thing, but returns a DateTime. The PR also rewrites tests to expect the DateTime format for the UTC zone, '+00:00', rather than 'UTC'.
> Making sure Valkyrie uses DateTime consistently.

- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- spec/valkyrie/persistence/fedora/orm_converter_spec.rb
Prior to this commit, our language of Blacklist perpetuated the idea
that "black" is not allowed. This change clarifies the purpose without
relying on discriminatory cultural jargon (e.g. blacklist/whitelist). In
addition, by using a clear term, we make the intention more accessible.
Closes #832
> Renaming Blacklist to Denylist

- valkyrie.gemspec
RDF.rb 3.0.x doesn't support Ruby 3. there is (hopefully) no need to lock the
dependency so tightly, since the RDF gems carefully follow SemVer.
> loosen `rdf` dependency to allow 3.1+

- .circleci/config.yml
This adds a test in CircleCI that will fail if there is a branch called "master" on the remote.  This is intended to help report on errors if any contributor mistakenly pushes an old branch from a local fork.
> Adds test for branch name to CircleCI

- CONTRIBUTING.md
- README.md
> Updated README and CONTRIBUTING guidelines

- lib/valkyrie/persistence/solr/model_converter.rb
Reducing Array.wrap and not processing Nil values speeds up the model
converter significantly.
> Improve ModelConverter performance.

- lib/valkyrie/persistence/solr/metadata_adapter.rb
- lib/valkyrie/persistence/solr/persister.rb
- lib/valkyrie/persistence/solr/repository.rb
- lib/valkyrie/specs/shared_specs.rb
- lib/valkyrie/specs/shared_specs/write_only/metadata_adapter.rb
- spec/valkyrie/persistence/solr/metadata_adapter_spec.rb
The first iteration just doesn't enforce a bunch of the shared specs and
expects a simple `true` response to save/save_all.
This adds a write_only mode to the solr persister which is a little
faster, but won't be the final state of solr indexing support.
> Initial run at shared write-only persisters.

- lib/valkyrie/persistence/custom_query_container.rb
- lib/valkyrie/specs/shared_specs/queries.rb
the custom query container used to raise:
NoMethodError: undefined method 'new' for nil:NilClass`
this error doesn't do much to help callers figure out where they've gone
awry. the updated message includes:
- the originally called method name
- the list of available methods to call (as a kind of 'did you mean' feature)
- reference to the idea that queries need to be registered
hopefully these are all helpful reminders in dubugging.
> raise a more informative NoMethodError for missing custom queries

- lib/valkyrie/persistence/custom_query_container.rb
I'm not sure what the performance will be like, but this is definitely
simpler.
> Refactor away from method_missing for custom_query_container.

- lib/valkyrie/storage/disk.rb
- spec/valkyrie/storage/disk_spec.rb
when using multiple disk adapters targeting different `base_path`s on the local
disk, `Valkyrie::StorageAdapter.adapter_for(id: 'disk:///some/path/image.jpg')`
should match against the adapter handling `/some/path`. the original
implementation used whichever adapter was registered first chronologically.
targeting the `.handles?` implementation on `base_path` makes it possible to
resolve existing identifiers dynamically in this case.
> support discovery of multiple disk adapters on different paths

- lib/valkyrie.rb
We first noticed issues in Ruby 3 trying to do
```rb
Valkyrie::Config.new.resource_class_resolver
```
It returned `nil` even though in this case the default resource class resolver was defined. The same problem appears to exist for other Config methods. Changing them to use `self[:method_name]` instead of `super` circumvents the issue, which appears to be a bug in OpenStruct, probably with Ruby 3.
> Use brackets instead of super in Config methods

- lib/valkyrie/persistence/custom_query_container.rb
- lib/valkyrie/specs/shared_specs/queries.rb
This is required for Ruby 3 compatibility:
<https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/>.
> Explicitly handle keyword arguments in queries

- .circleci/config.yml
- lib/valkyrie/persistence/fedora/ordered_list.rb
- spec/support/fedora_helper.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- spec/valkyrie/persistence/fedora/persister/model_converter_spec.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
- spec/valkyrie/persistence/fedora/query_service_spec.rb
- spec/valkyrie/storage/fedora_spec.rb
Adds tests for ruby 3.0, 3.1, and 3.2
> Test with latest ruby versions

- lib/valkyrie/specs/shared_specs/storage_adapter.rb
in some contexts(?) awk can fail to filter results correctly:
```
[3] pry(RSpec::Support::AllExceptionsExceptOnesWeMustNotRescue)> `lsof +D . | awk '{print $9}'` => "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" [4] 
pry(RSpec::Support::AllExceptionsExceptOnesWeMustNotRescue)> `lsof +D .` => "1\t/usr/local/bin/ruby\t0\t/dev/pts/0\n1\t/usr/local/bin/ruby\t1\t/dev/pts/0\n1\t/usr/local/bin/ruby\t2\t/dev/pts/0\n1\t/usr/local/bin/ruby\t3\tanon_inode:[eventfd]\n1\t/usr/local/bin/ruby\t4\tanon_inode:[eventfd]\n1\t/usr/local/bin/ruby\t5\tpipe:[39924]\n1\t/usr/local/bin/ruby\t6\tpipe:[39924]\n1\t/usr/local/bin/ruby\t7\t/app/samvera/hyrax-engine/config/metadata/core_metadata.yaml\n1\t/usr/local/bin/ruby\t8\tanon_inode:inotify\n1\t/usr/local/bin/ruby\t9\tpipe:[39 …
```
> avoid using awk in shared specs

- lib/valkyrie/change_set.rb
@jeremyf [made this patch for Valkyrie 2.2](https://github.com/samvera/valkyrie/commit/0638a779fc1576f9ee74960a95d48682272f0e81); this is for 3.0.
Addresses a problem reported by @ShanaLMoore when using valkyrie with reform 0.2.4:
```/usr/local/lib/ruby/2.7.0/forwardable.rb:130:in `instance_delegate': wrong number of arguments (given 2, expected 1) (ArgumentError)```
Can be seen during a hyrax test app build [here](https://app.circleci.com/pipelines/github/samvera/hyrax/8917/workflows/f9020f5d-1d74-4710-b85e-d46fbbe4c062/jobs/68447)
Thought to be related to https://github.com/trailblazer/reform-rails/issues/99
> Removing delegate in favor of explicit method

- .circleci/config.yml
- .lando.yml
- .rubocop_todo.yml
- lib/valkyrie/specs/shared_specs/storage_adapter.rb
- lib/valkyrie/storage.rb
- lib/valkyrie/storage/disk.rb
- lib/valkyrie/storage/fedora.rb
- lib/valkyrie/storage/memory.rb
- lib/valkyrie/storage/versioned_disk.rb
- lib/valkyrie/storage_adapter.rb
- spec/spec_helper.rb
- spec/support/fedora_helper.rb
- spec/valkyrie/storage/disk_spec.rb
- spec/valkyrie/storage/fedora_spec.rb
- spec/valkyrie/storage/versioned_disk_spec.rb
This adds a versioning implementation to Valkyrie StorageAdapters and implements it for a new versioned disk adapter and Fedora 4/5/6.
There's a follow-on ticket to do here: https://github.com/samvera/valkyrie/issues/934
As this doesn't change the API or outcomes of any of the adapters this is a minor release.
> StorageAdapter Versioning Implementation

- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
I am currently working on fixing some permission issues in a Hyrax/Fedora 6 setup using the Valkyrie Fedora adapter. The underlying issue is tied to the `Hyrax::Permission`  `:mode`  attribute, which is of type `Valkyrie::Types::Coercible::Symbol` , not saving correctly on Fedora 6 using the Valkyrie adapter.
Since the type we are trying to support is `Valkyrie::Types::Coercible::Symbol`, identifying `Symbol` values in the `ModelConverter` of the Fedora Persister and converting them to `String` values resolves the issues we are encountering.
> Add support for coercible symbols in the Fedora persister

- CHANGELOG.md
- lib/valkyrie/specs/shared_specs/storage_adapter.rb
- spec/spec_helper.rb
- spec/support/fixture_path.rb
- spec/valkyrie/storage/disk_spec.rb
- spec/valkyrie/storage/versioned_disk_spec.rb
- spec/valkyrie/storage_adapter/file_spec.rb
- spec/valkyrie_spec.rb
This allows for downstream implementations to not require setting a `ROOT_PATH` constant—one that is general in name—in specs.
> ♻️ Favor Engine's root path instead of ROOT_PATH

- valkyrie.gemspec
Given that the shared specs reference spec/fixtures, and those shared specs are used by downstream implementations, we need to ensure that the spec/fixtures are part of the Gemfile.
This problem was brought further to light by the following PR:
- https://github.com/samvera/valkyrie/pull/942
Prior to #942's introducing, each downstream implementation needed to create a `ROOT_PATH` constant to leverage the shared specs AND provide their own spec/fixtures.
To verify this logic, I checked the command line:
```ruby
irb> files = `git ls-files -z`.split("\x0").reject do |f|
f.match(%r{^(test|spec|features)}) && !f.start_with?("spec/fixtures")
end
=> [".circleci/config.yml",
...
irb> files.size
144
irb> files.map { |f| f.split("/")[0..1].join("/") }.uniq
=>
[".circleci/config.yml",
".ctags", …
```
> 🐛 Include spec/fixture files as part of gem

- lib/valkyrie/specs/shared_specs/change_set.rb
This test is fragile in that it does not account for the fact that we
can specify a :prepopulate option for a property.
When you specify the `:prepopulate` option (as in
`Hyrax::Form::PcdmCollection`) and use this shared spec, then the now
deleted spec fails with no recourse.
Related to:
- https://github.com/samvera/hyrax/issues/6702
- https://github.com/samvera/hyrax/pull/6703
> ☑️ Remove ChangeSet#prepopulate! test

- lib/valkyrie.rb
- lib/valkyrie/specs/shared_specs/storage_adapter.rb
- spec/valkyrie_spec.rb
Upstream gems shouldn't have to load a Rails engine or be a Rails dependency to use shared specs.
> Add new #root_path helper

- lib/valkyrie/storage_adapter.rb
- spec/valkyrie/storage_adapter_spec.rb
Also:
- Corrects the documentation of Valkyrie::StorageAdapter::File#valid?
- Implements AdapterNotFoundError as documented on Valkyrie::StorageAdapter.find and in test description. (I'm not sure if this would technically be a breaking change since the raised exception would not be a RuntimeError.)
> Addresses documentation issue in #951

- README.md
- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/storage/fedora.rb
- spec/support/fedora_helper.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- spec/valkyrie/storage/fedora_spec.rb
Fedora 6.5 now supports automatic creation of "pairtree" IDs, which means that identifiers are stored in a hashed directory structure to avoid excessive child nodes directly in the root node. 
However, unlike Fedora 4 where this was the default behavior, it has to be enabled via options in 6.5.  Since doing so requires configuring both the count and length of the pairtree algorithm, it needs to be configurable in the Valkyrie Fedora adapters so that both sides match.
This PR adds new parameters to the adapter classes to set the pairtree count and length, which are used to determine if pairtrees are enabled to affect ID to URI translations.
It carefully preserves existing behaviors as the defaults so that this is not a breaking change.  So, based on the Fedora version sent by the …
> Support for configurable pairtree IDs in Fedora 6

- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- lib/valkyrie/persistence/fedora/metadata_adapter.rb: stops sending empty string values to `#pair_path` and associated errors.
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb: tests the added protective return of nil.
> Returns nil when #id_to_uri is passed empty strings.

- lib/valkyrie/persistence/fedora/query_service.rb
- spec/valkyrie/persistence/fedora/persister/model_converter_spec.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
- spec/valkyrie/persistence/fedora/query_service_spec.rb
Support for pairtree paths in Fedora was added in #957, which was initially working per desk checking behaviors from within the Hyrax Sirenia app.  But before final approval/merge, 957 was refactored to require setting the Fedora major/minor version at 6.5 to get pairtree paths.  
When Hyrax finally picked up the 3.3.0 Valkyrie gem with pairtree support, it caused major breakage across many aspects of works and relationships.  That's because the refactor to require `fedora_version = 6.5` overlooked a bit of code in the query service that was checking major version only (5 or 6) to decide how to build related URIs.
> Fixing related URIs to account for minor versions set in fedora_version

- lib/valkyrie.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
To configure string length threshold above which a value is indexed only as :tsim.
Fixes #961
> Adds config setting index_tsim_only_threshold

- lib/valkyrie.rb
- lib/valkyrie/persistence/shared/json_value_mapper.rb
Default value is `true` to preserve current behavior. Setting the value to `false` bypasses registration of the `DateTime` value mapper which handles the ISO8601 date/time string to Ruby DateTime casting.
Fixes #747 
Let me know if I should add a test; there are no tests for the existing functionality.
> Provides new boolean configuration setting `auto_cast_iso8601_as_datetime'

- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
Fixes #970 
Fedora's criteria for determining if a property is server managed has been more selective than Valkyrie's. Relevant docs and code:
https://wiki.lyrasis.org/display/FEDORA6x/Server+Managed+Triples
https://github.com/fcrepo/fcrepo/blob/1cae11d1bfb1fda3ddd39f0ab8c01f780f3c3432/fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/RdfLexicon.java#L74-L75
The spec is based on the needs of the Hyrax ResourceStatus service.
> Align behavior of server managed properties with Fedora.

- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
With fedora, If an empty string is passed to find_by it gets changed into a nil by id_to_uri. That nil will later cause InvalidURIError to be raised where other adapters will raise ObjectNotFound. This aligns the behavior of the fedora adapter with the others, and adds some checks in the shared spec.
> Check for nil id to avoid InvalidURIError

- lib/valkyrie/specs/shared_specs/storage_adapter.rb
- lib/valkyrie/storage/disk.rb
- lib/valkyrie/storage/fedora.rb
- lib/valkyrie/storage/memory.rb
- lib/valkyrie/storage/versioned_disk.rb
Having this available will ease writing tests for systems that use multiple storage adapters. The fedora storage adapter already does this.
Hyrax has a couple specs that stub in file identifiers, but with fedora storage in the mix it could not find the appropriate storage adapter.
> Make storage adapters report their protocol string
