samvera/valkyrie

- README.md
- config/database.yml.example
Some basic directions for getting Valkyrie up and running on an OS X dev box, seems to work for us.
> start doing install directions

- app/adapters/adapter_container.rb
- app/controllers/concerns/model_controller_behavior.rb
- app/persisters/parent_cleanup_persister.rb
- config/initializers/register_adapters.rb
- lib/valkyrie/specs/shared_specs/adapter.rb
- script/benchmarker.rb
- spec/adapters/registered_adapter_spec.rb
- spec/controllers/catalog_controller_spec.rb
This adds a test for all registered adapters to ensure they're adapters
and re-enables the composite adapter for benchmarking.
Closes #11
> Fix registered composite adapter.

- app/persistence/valkyrie/persistence/postgres/orm/resource.rb
- app/persistence/valkyrie/persistence/solr/mapper.rb
- app/persistence/valkyrie/persistence/solr/resource_factory.rb
- config/initializers/rdf_literal_as_json.rb
- lib/valkyrie/specs/shared_specs/persister.rb
I mostly did this to see how hard it would be to add another data-type.
> Add RDF::URI Support.

- app/controllers/concerns/catalog.rb
- app/controllers/downloads_controller.rb
- app/decorators/file_set_decorator.rb
- app/decorators/valkyrie/model_decorator.rb
- app/models/file_node.rb
- app/persisters/file_set_appending_persister.rb
- app/views/books/_form.html.erb
- app/views/catalog/_members_default.html.erb
- config/role_map.yml
- config/routes.rb
- lib/valkyrie/file_repository.rb
- lib/valkyrie/id.rb
- lib/valkyrie/persistence/active_fedora/dynamic_klass.rb
- lib/valkyrie/persistence/active_fedora/orm/resource.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- lib/valkyrie/specs/shared_specs/storage_adapter.rb
- lib/valkyrie/types.rb
- spec/controllers/books_controller_spec.rb
- spec/controllers/downloads_controller_spec.rb
- spec/decorators/valkyrie/model_decorator_spec.rb
- spec/repositories/valkyrie/file_repository_spec.rb
- spec/views/catalog/_members_default.html.erb_spec.rb
Using the Hydra behavior now because there's been lots of work over the
years to handle streaming content. This is confirmed to work for both
the Memory and Disk adapter.
> First pass at downloading files.

- app/controllers/concerns/catalog.rb
- app/forms/book_form.rb
- app/forms/collection_form.rb
- app/forms/file_set_form.rb
- app/forms/page_form.rb
- db/migrate/20170531004548_change_model_type_to_internal_model.rb
- db/schema.rb
- lib/valkyrie/form.rb
- lib/valkyrie/model.rb
- lib/valkyrie/persistence/active_fedora/dynamic_klass.rb
- lib/valkyrie/persistence/active_fedora/orm/resource.rb
- lib/valkyrie/persistence/active_fedora/resource_factory.rb
- lib/valkyrie/persistence/postgres/dynamic_klass.rb
- lib/valkyrie/persistence/postgres/orm/resource.rb
- lib/valkyrie/persistence/postgres/queries/find_all_query.rb
- lib/valkyrie/persistence/postgres/resource_factory.rb
- lib/valkyrie/persistence/solr/queries/find_all_query.rb
- lib/valkyrie/persistence/solr/resource_factory.rb
- lib/valkyrie/specs/shared_specs/model.rb
Extracted from NestedResources PR. This gives each of the adapters a
standard place to check for an internal model, and a pattern for
inheritable default properties on Valkyrie::Model.
> Standardize on internal_model

- lib/valkyrie/persistence/solr/mapper.rb
- lib/valkyrie/persistence/solr/resource_factory.rb
- spec/valkyrie/persistence/solr/mapper_spec.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
> Use tsim only for really long properties.

- lib/valkyrie/model.rb
- lib/valkyrie/persistence/active_fedora/dynamic_klass.rb
- lib/valkyrie/persistence/active_fedora/orm/resource.rb
- lib/valkyrie/persistence/active_fedora/persister.rb
- lib/valkyrie/persistence/postgres/orm/resource.rb
- lib/valkyrie/persistence/solr/mapper.rb
- lib/valkyrie/persistence/solr/resource_factory.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- lib/valkyrie/types.rb
- spec/valkyrie/persistence/active_fedora/persister_spec.rb
- spec/valkyrie/persistence/solr/mapper_spec.rb
Okay, so I got this to work.
However:
The ActiveFedora version of this is super finicky. It doesn't support arbitrarily deep nesting OR mixed values (so a string and a nested resource in the same property). It also requires configuration of the ActiveFedora resource, which isn't actually a configurable property of the adapter yet.
All the other adapters were pretty straight forward, but the solr one will never support searching (if that becomes a requirement) because it has to serialize the resources to JSON and back.
So...what's everyone think?
> [FOR DISCUSSION] Nested resources

- lib/valkyrie/persistence/active_fedora/orm/resource.rb
- spec/factories/admins.rb
- spec/models/user_spec.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
> Using example.com instead of test.com for bogus URLs

- .rubocop.yml
- app/derivative_services/image_derivative_service.rb
- app/persisters/indexing_persister.rb
- config/initializers/register_adapters.rb
- lib/valkyrie/controller_concerns/model_controller_behavior.rb
- script/benchmarker.rb
- spec/persisters/indexing_persister_spec.rb
- valkyrie/lib/valkyrie/persistence/buffered_persister.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
This builds a persister which indexes automatically, and also provides a method to buffer indexing until the end of the operation.
The benchmark script is updated to take advantage of this. You can see the difference between buffering/not buffering by comparing the `index_solr` and `indexing_persister` adapters:
```
valkyrie indexing_persister % rails runner script/benchmarker.rb
Running via Spring preloader in process 15027
user     system      total        real
postgres create 1000 children  1.970000   0.250000   2.220000 (  2.642561)
postgres save parent with 1000 children  0.040000   0.000000   0.040000 (  0.048906)
postgres reload parent with 1000 children  0.010000   0.000000   0.010000 (  0.009415)
postgres add one more page to a parent with 1000 existing children  0.100000 …
```
> Indexing persister

- valkyrie/README.md
- valkyrie/lib/generators/valkyrie/model_generator.rb
- valkyrie/lib/generators/valkyrie/templates/model.rb.erb
- valkyrie/lib/generators/valkyrie/templates/model_spec.rb.erb
- valkyrie/lib/valkyrie.rb
- valkyrie/spec/valkyrie/generators/valkyrie/model_generator_spec.rb
> Adding model generator

- config/initializers/valkyrie.rb
- lib/valkyrie/persistence/active_fedora/adapter.rb
- lib/valkyrie/persistence/active_fedora/persister.rb
- spec/valkyrie/persistence/active_fedora/adapter_spec.rb
- spec/valkyrie/persistence/active_fedora/query_service_spec.rb
- valkyrie/lib/valkyrie/persistence/postgres/adapter.rb
- valkyrie/lib/valkyrie/persistence/postgres/persister.rb
- valkyrie/spec/valkyrie/persistence/postgres/adapter_spec.rb
- valkyrie/spec/valkyrie/persistence/postgres/queries/find_members_query_spec.rb
- valkyrie/spec/valkyrie/persistence/postgres/query_service_spec.rb
> Make adapters into instances

- config/initializers/time_encoding_precision.rb
- lib/valkyrie/persistence/active_fedora/dynamic_klass.rb
- lib/valkyrie/persistence/active_fedora/resource_factory.rb
- valkyrie/lib/valkyrie/persistence/memory/persister.rb
- valkyrie/lib/valkyrie/persistence/postgres/orm/resource.rb
- valkyrie/lib/valkyrie/persistence/solr/mapper.rb
- valkyrie/lib/valkyrie/persistence/solr/resource_factory.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
> Support DateTime

- lib/valkyrie/persistence/active_fedora/persister.rb
- spec/persisters/appending_persister_spec.rb
- spec/persisters/file_set_appending_persister_spec.rb
- spec/persisters/indexing_persister_spec.rb
- spec/persisters/parent_cleanup_persister_spec.rb
- spec/valkyrie/persistence/active_fedora/persister_spec.rb
- valkyrie/lib/valkyrie/persistence/postgres/persister.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
- valkyrie/spec/valkyrie/persistence/buffered_persister_spec.rb
- valkyrie/spec/valkyrie/persistence/composite_persister_spec.rb
- valkyrie/spec/valkyrie/persistence/delete_tracking_buffer_spec.rb
- valkyrie/spec/valkyrie/persistence/memory/persister_spec.rb
- valkyrie/spec/valkyrie/persistence/postgres/persister_spec.rb
- valkyrie/spec/valkyrie/persistence/solr/persister_spec.rb
Fixes https://github.com/samvera-labs/valkyrie/issues/137
> The adapter method is unnecessary on the presenter

- config/initializers/valkyrie.rb
- valkyrie/lib/valkyrie/specs/shared_specs/storage_adapter.rb
- valkyrie/lib/valkyrie/storage_adapter.rb
- valkyrie/spec/spec_helper.rb
- valkyrie/spec/valkyrie/id_spec.rb
- valkyrie/spec/valkyrie/storage_adapter/fedora_spec.rb
> Fedora storage adapter

- .gitignore
- README.md
- valkyrie/.gitignore
- valkyrie/README.md
> Expanding READMEs (particularly the gem README) with usage examples, setup instructions, etc.

- config/initializers/valkyrie.rb
- valkyrie/README.md
- valkyrie/lib/valkyrie.rb
- valkyrie/lib/valkyrie/storage.rb
- valkyrie/lib/valkyrie/storage/disk.rb
- valkyrie/lib/valkyrie/storage/fedora.rb
- valkyrie/lib/valkyrie/storage/memory.rb
- valkyrie/lib/valkyrie/storage_adapter.rb
- valkyrie/spec/valkyrie/storage/disk_spec.rb
- valkyrie/spec/valkyrie/storage/fedora_spec.rb
- valkyrie/spec/valkyrie/storage/memory_spec.rb
- valkyrie/spec/valkyrie/storage_adapter_spec.rb
- valkyrie/spec/valkyrie_spec.rb
> Breaking StorageAdapter implementations into their own class files

- valkyrie/lib/valkyrie/persistence/composite_persister.rb
- valkyrie/lib/valkyrie/persistence/memory/persister.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
- valkyrie/spec/valkyrie/generators/valkyrie/model_generator_spec.rb
> Adding missing test coverage

- README.md
> Adding shared spec docs

- valkyrie/lib/valkyrie/resource.rb
- valkyrie/spec/valkyrie/resource_spec.rb
> Add class-level model_name

- valkyrie/lib/valkyrie/persistence/postgres/orm/resource.rb
It's really slow to run regex on every value.
> Don't regexp date unless necessary.

- valkyrie/lib/valkyrie/persistence.rb
- valkyrie/lib/valkyrie/persistence/fedora.rb
- valkyrie/lib/valkyrie/persistence/fedora/list_node.rb
- valkyrie/lib/valkyrie/persistence/fedora/metadata_adapter.rb
- valkyrie/lib/valkyrie/persistence/fedora/ordered_list.rb
- valkyrie/lib/valkyrie/persistence/fedora/ordered_reader.rb
- valkyrie/lib/valkyrie/persistence/fedora/persister.rb
- valkyrie/lib/valkyrie/persistence/fedora/persister/model_converter.rb
- valkyrie/lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- valkyrie/lib/valkyrie/persistence/fedora/persister/resource_factory.rb
- valkyrie/lib/valkyrie/persistence/fedora/query_service.rb
- valkyrie/lib/valkyrie/persistence/postgres/queries/find_references_query.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
- valkyrie/lib/valkyrie/specs/shared_specs/queries.rb
- valkyrie/spec/support/wipe_raw_fedora_adapter.rb
- valkyrie/spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- valkyrie/spec/valkyrie/persistence/fedora/persister_spec.rb
- valkyrie/spec/valkyrie/persistence/fedora/query_service_spec.rb
This is a Fedora adapter without using ActiveFedora. It supports arbitrarily nested resources, but can't finish benchmarks for 1000 members (the 100 member benchmark is significantly faster than the AF implementation.) Not sure why - haven't had time to dig into it.
> Raw fedora adapter

- valkyrie/lib/valkyrie.rb
- valkyrie/lib/valkyrie/resource.rb
- valkyrie/spec/valkyrie_spec.rb
Speeds up staging in Figgy for operations which need to do a lot of queries and handle many (> 1000) resources.
> Cache Config

- valkyrie/lib/valkyrie/persistence/solr/resource_factory.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
Alternative implementation of #205
> Check for nested URI support.

- valkyrie/lib/valkyrie/storage/disk.rb
> Configurable bucketed path.

- app/views/catalog/_members_default.html.erb
- config/blacklight.yml
- config/fedora.yml
- config/solr.yml
- lib/tasks/dev.rake
- lib/valkyrie/persistence/active_fedora/orm/resource.rb
- valkyrie/Gemfile
- valkyrie/lib/valkyrie/storage/disk.rb
- valkyrie/valkyrie.gemspec
The decorators are returning Strings so the call to to_sentence breaks, connects to #179
> Decorators return first entry in array so to_sentence not needed

- valkyrie/lib/valkyrie/storage/disk.rb
Useful for Figgy, which sometimes needs to make hard links.
> Add configurable file mover.

- valkyrie/valkyrie.gemspec
Resolves #193 by adding the latest release of the "json" Gem as a dependency
> Adds JSON as a Gem dependency

- app/controllers/books_controller.rb
- app/decorators/page_decorator.rb
- lib/valkyrie/controller_concerns/model_controller_behavior.rb
- spec/controllers/books_controller_spec.rb
> Incorrect labels in forms as Pages were being created as Books

- lib/valkyrie/controller_concerns/model_controller_behavior.rb
> Update action directs to catalog show without breadcrumbs

- README.md
> Add to README for setting up / testing the gem

- .rubocop.yml
- app/persisters/indexing_adapter.rb
- lib/valkyrie/persistence/active_fedora/persister.rb
- valkyrie/lib/valkyrie/persistence/buffered_persister.rb
- valkyrie/lib/valkyrie/persistence/composite_persister.rb
- valkyrie/lib/valkyrie/persistence/fedora/metadata_adapter.rb
- valkyrie/lib/valkyrie/persistence/fedora/persister.rb
- valkyrie/lib/valkyrie/persistence/memory/persister.rb
- valkyrie/lib/valkyrie/persistence/postgres/persister.rb
- valkyrie/lib/valkyrie/persistence/solr/persister.rb
- valkyrie/lib/valkyrie/specs/shared_specs/persister.rb
- valkyrie/spec/support/wipe_raw_fedora_adapter.rb
> Add `#wipe!` to metadata persisters

- valkyrie/lib/valkyrie/specs/shared_specs/storage_adapter.rb
- valkyrie/lib/valkyrie/storage/disk.rb
- valkyrie/lib/valkyrie/storage/fedora.rb
- valkyrie/lib/valkyrie/storage/memory.rb
- valkyrie/lib/valkyrie/storage_adapter.rb
- valkyrie/spec/valkyrie/storage_adapter_spec.rb
> Add delete to StorageAdapters.

- .rubocop.yml
- README.md
Based on my understanding of the code-base, as well some face to face
demonstrations, this is my best effort to help people quickly orient
to Valkyrie's current top-level file structure.
> Adding orientation documentation

- db/migrate/20171011224518_create_path_gin_index.valkyrie_engine.rb
- db/schema.rb
- valkyrie/db/migrate/20171011224121_create_path_gin_index.rb
Makes for much faster `@>` queries in postgres.
> Add jsonb_path_ops index.

- lib/valkyrie/persistence/active_fedora/query_service.rb
- valkyrie/lib/valkyrie/persistence/fedora/query_service.rb
- valkyrie/lib/valkyrie/persistence/memory/query_service.rb
- valkyrie/lib/valkyrie/persistence/postgres/query_service.rb
- valkyrie/lib/valkyrie/persistence/solr/query_service.rb
- valkyrie/lib/valkyrie/specs/shared_specs/queries.rb
> Ensure the value passed to find_by(id:) is a Valkyrie::ID

- valkyrie/lib/valkyrie/persistence/postgres/query_service.rb
> Faster inverse_references query for postgres.

- valkyrie/lib/valkyrie/types.rb
- valkyrie/spec/valkyrie/types_spec.rb
This seems worth of promoting up to Valkyrie:
https://github.com/pulibrary/figgy/blob/master/app/types/types.rb#L4
> Add URI to Valkyrie Types

- spec/change_sets/book_change_set_spec.rb
- spec/change_sets/song_change_set_spec.rb
- valkyrie/lib/valkyrie/change_set.rb
> clear the errors collection on #valid?

- valkyrie/lib/valkyrie/persistence/memory/query_service.rb
Add documentation about its return value
> Move member_ids to private visibility

- valkyrie/spec/support/solr_test.rb
- valkyrie/spec/valkyrie/persistence/solr/query_service_spec.rb
This improved my test time from 5.83 seconds to 4.13 seconds.
> Only clear solr where needed

- lib/valkyrie/persistence/solr/model_converter.rb
- spec/spec_helper.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
- spec/valkyrie/persistence/solr/query_service_spec.rb
> Give a friendly error when the property can't be converted

- spec/valkyrie/types_spec.rb
> Adding test for nil input to URI type

- spec/valkyrie/resource_spec.rb
ref #325
Co-authored-by: Carolyn Cole <cam156@psu.edu>
> Adding test for human_readble_type setter

- lib/valkyrie/change_set.rb
- spec/valkyrie/change_set_spec.rb
Also refactors code for clarity
> Add test for valid? to change set. refs #325

- lib/valkyrie/persistence.rb
- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/memory/persister.rb
- lib/valkyrie/persistence/postgres/persister.rb
- lib/valkyrie/persistence/solr/repository.rb
- lib/valkyrie/specs/shared_specs/persister.rb
> Raise an error if persisting a scalar.

- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
> Allow a string for find_by(id:)

- lib/valkyrie/persistence/solr/persister.rb
> Document use of dynamic fields in solr persister 

- lib/valkyrie/persistence.rb
- lib/valkyrie/persistence/buffered_persister.rb
- lib/valkyrie/persistence/composite_persister.rb
- lib/valkyrie/persistence/custom_query_container.rb
- lib/valkyrie/persistence/delete_tracking_buffer.rb
- lib/valkyrie/persistence/fedora.rb
- lib/valkyrie/persistence/memory.rb
- lib/valkyrie/persistence/postgres.rb
- lib/valkyrie/persistence/solr.rb
refs #353
Included example code snippets where applicatble
> Adding header level comments for Persister tree

- lib/valkyrie/persistence/memory.rb
- lib/valkyrie/storage.rb
- lib/valkyrie/storage/disk.rb
- lib/valkyrie/storage/fedora.rb
- lib/valkyrie/storage/memory.rb
> Add class-level documentation to storage classes

- lib/valkyrie/resource.rb
- lib/valkyrie/resource/access_controls.rb
> Adding header comments to resource classes

- lib/valkyrie/id.rb
- lib/valkyrie/metadata_adapter.rb
- lib/valkyrie/storage_adapter.rb
- lib/valkyrie/types.rb
> Finish class-level code docs for all files in valkyrie/lib/valkyrie

- lib/valkyrie/indexers/access_controls_indexer.rb
- lib/valkyrie/resource/access_controls.rb
> Adding header comments to AccessControlsIndexer

- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
> Ensure resource is saved

- .rubocop.yml
- Rakefile
- tasks/dev.rake
> Move rake tasks

- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
fixes #384
fixes #387
Added tests for future type support
Write Time to fedora as a custom datatype
> Write Integer and DateTime to fedora as custom datatypes

- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
fixes #296
Note the removal of present? in the Set type was needed to support boolean becuase flase.present? is flase
> Adding support for Boolean

- lib/valkyrie/change_set.rb
- spec/valkyrie/change_set_spec.rb
Was necessary when upgrading Figgy.
> Add missing model_for_property

- .rubocop.yml
- .rubocop_todo.yml
- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/queries.rb
- lib/valkyrie/persistence/solr/queries/find_many_by_ids_query.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
Add spec
Add fedora query
Add memory query
Add postgres query
Add solr query
> Add find_many_by_ids query, fixes #284

- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
Was a regression caused by switch to Array.wrap.
> Fix problem with Set types creating nested objects

- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
Got removed when checking for blank? was removed.
> Re-instate collapsing blank Valkyrie IDs.

- README.md
As I was familiarizing myself with Valkyrie I found a few bugs in the README
> updates readme bugs and clarity

- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- spec/valkyrie/persistence/fedora/permissive_schema_spec.rb
- spec/valkyrie/types_spec.rb
> Add tests to improve coverage.

- lib/valkyrie/persistence/postgres/orm_converter.rb
By ignoring nil values in the hash which will get handled by dry-types
we're doing significantly less work for large Valkyrie::Resource
schemas.
> Significantly speed up Postgres ORMConverter.

- lib/valkyrie/persistence/postgres/orm_converter.rb
- lib/valkyrie/persistence/postgres/persister.rb
- lib/valkyrie/persistence/postgres/resource_converter.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
> Add postgres single-valued support.

- lib/valkyrie/persistence.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/locking_query.rb
- spec/valkyrie/persistence/solr/query_service_spec.rb
- spec/valkyrie/persistence_spec.rb
- spec/valkyrie/resource_spec.rb
> Replaces optimistic_lock_token method with a Constant

- lib/valkyrie/persistence/solr/model_converter.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
> Index single value fields for sortable support.

- lib/valkyrie/persistence/postgres/metadata_adapter.rb
- lib/valkyrie/persistence/postgres/query_service.rb
This aligns the Postgres::QueryService with the Solr:QueryService
> Inject resource_factory into the Pg QueryService

- lib/valkyrie/persistence/postgres/resource_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
> Fix single values returning an array in Postgres.

- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/persistence/memory/metadata_adapter.rb
- lib/valkyrie/persistence/postgres/metadata_adapter.rb
- lib/valkyrie/persistence/solr/metadata_adapter.rb
- lib/valkyrie/specs/shared_specs/metadata_adapter.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- spec/valkyrie/persistence/memory/metadata_adapter_spec.rb
- spec/valkyrie/persistence/postgres/metadata_adapter_spec.rb
- spec/valkyrie/persistence/solr/metadata_adapter_spec.rb
> Add shared spec and implementations for adapter_id

- lib/valkyrie/persistence.rb
- lib/valkyrie/persistence/optimistic_lock_token.rb
- spec/valkyrie/persistence/optimistic_lock_token_spec.rb
> Valkyrie::Persistence::OptimisticLockToken

- README.md
- lib/generators/valkyrie/templates/resource.rb.erb
- lib/valkyrie/persistence/fedora/persister/alternate_identifier.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/resource/access_controls.rb
- lib/valkyrie/specs/shared_specs/change_set_persister.rb
- lib/valkyrie/specs/shared_specs/locking_persister.rb
- lib/valkyrie/specs/shared_specs/locking_query.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- lib/valkyrie/specs/shared_specs/queries.rb
- lib/valkyrie/specs/shared_specs/resource.rb
- lib/valkyrie/specs/shared_specs/storage_adapter.rb
- lib/valkyrie/types.rb
- spec/valkyrie/persistence/buffered_persister_spec.rb
- spec/valkyrie/persistence/delete_tracking_buffer_spec.rb
- spec/valkyrie/persistence/fedora/persister/model_converter_spec.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
- spec/valkyrie/persistence/solr/composite_indexer_spec.rb
- spec/valkyrie/persistence/solr/model_converter_spec.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
- spec/valkyrie/persistence/solr/query_service_spec.rb
- spec/valkyrie/resource_spec.rb
> Add ID property by default.

- lib/valkyrie/persistence/postgres/persister.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
> Postgres persister uses transactions for save_all

- lib/valkyrie.rb
- lib/valkyrie/persistence.rb
- lib/valkyrie/persistence/fedora.rb
- spec/spec_helper.rb
Prevents loading some dependencies like AF if an application isn't using
them.
Closes #201.
> Autoload persistence adapters

- lib/valkyrie/persistence.rb
- lib/valkyrie/persistence/optimistic_lock_token.rb
- lib/valkyrie/persistence/solr/metadata_adapter.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/persistence/solr/resource_factory.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/locking_persister.rb
- lib/valkyrie/types.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
- spec/valkyrie/persistence/solr/query_service_spec.rb
- spec/valkyrie/resource_spec.rb
- spec/valkyrie/types_spec.rb
>  Adds Valkyrie::Types::OptimisticLockToken and uses it in Solr

- README.md
Resolves #451 by providing links to the related Wiki page (as well as other pages where appropriate)
> Linking to the appropriate pages in the Wiki within the README document

- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/optimistic_lock_token.rb
- spec/valkyrie/persistence/optimistic_lock_token_spec.rb
> Add comparison method to OptimisticLockToken

- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- lib/valkyrie/specs/shared_specs/queries.rb
> Prefer hash methods instead of calling .send on lock tokens

- .rubocop.yml
> Use "Naming" namespace in Rubocop instead of "Style"

- lib/valkyrie/resource.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
> Ensures that the PostgreSQL adapter persists ordered properties

- lib/valkyrie/change_set.rb
- lib/valkyrie/id.rb
- lib/valkyrie/metadata_adapter.rb
- lib/valkyrie/persistence/optimistic_lock_token.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/types.rb
Expanding and adding to the method comments, so that the comments also describe intent and not just how things work or appear in the UI.
> Adding or Improving Method-level Documentation in Files

- lib/valkyrie/persistence/fedora/list_node.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- spec/valkyrie/persistence/fedora/permissive_schema_spec.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
Fixes #495 
Alternative to #488
> Ordered properties fedora

- lib/valkyrie/id.rb
- lib/valkyrie/storage/fedora.rb
- spec/valkyrie/storage/fedora_spec.rb
Also depricates to_uri
fixes #550
> Removing reference to id.to_uri since that depends on ActiveFedora

- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/persister.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/persister.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/persister.rb
- lib/valkyrie/persistence/solr/query_service.rb
> Doc in code that persister, query service #initialize are not public API

- lib/valkyrie/persistence/fedora/list_node.rb
- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
> Ordering types: strings, ID, URI, DateTime, int,  float

- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/postgres/persister.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/persister.rb
- lib/valkyrie/persistence/solr/query_service.rb
> Only import the note in #initialize yardocs

- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/persister/orm_converter.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/valkyrie/persistence/fedora/persister_spec.rb
> Fix ordered nested objects in Fedora.

- lib/valkyrie/persistence/postgres/metadata_adapter.rb
- lib/valkyrie/persistence/postgres/orm.rb
- lib/valkyrie/persistence/postgres/orm_converter.rb
- lib/valkyrie/persistence/postgres/persister.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/postgres/resource_converter.rb
- lib/valkyrie/persistence/postgres/resource_factory.rb
> Extending the documentation for the PostgreSQL Persister and MetadataAdapter

- lib/valkyrie/persistence/solr/composite_indexer.rb
- lib/valkyrie/persistence/solr/metadata_adapter.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/persistence/solr/persister.rb
- lib/valkyrie/persistence/solr/queries/default_paginator.rb
- lib/valkyrie/persistence/solr/queries/find_all_query.rb
- lib/valkyrie/persistence/solr/queries/find_by_alternate_identifier_query.rb
- lib/valkyrie/persistence/solr/queries/find_by_id_query.rb
- lib/valkyrie/persistence/solr/queries/find_inverse_references_query.rb
- lib/valkyrie/persistence/solr/queries/find_many_by_ids_query.rb
- lib/valkyrie/persistence/solr/queries/find_members_query.rb
- lib/valkyrie/persistence/solr/queries/find_references_query.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/persistence/solr/repository.rb
- lib/valkyrie/persistence/solr/resource_factory.rb
> Increases the documentation for the Solr Persister and MetadataAdapter

- lib/generators/valkyrie/templates/resource_spec.rb.erb
https://github.com/samvera-labs/valkyrie/blob/master/lib/valkyrie/specs/shared_specs/resource.rb#L4
Fixes generator to create a basic spec that passes the shared specs.
> fixes generated spec to work with shared_specs expectation

- .docker-stack/valkyrie-development/docker-compose.yml
- .docker-stack/valkyrie-test/docker-compose.yml
- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/storage/fedora.rb
- tasks/dev.rake
I'd like to release `1.4.0` with Fedora support before `2.0`
> Finalize Fedora 5 Support

- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
> Deprecate .member

- lib/valkyrie/persistence/composite_persister.rb
> Fix up documentation for CompositePersister

- lib/valkyrie.rb
- lib/valkyrie/id.rb
- lib/valkyrie/persistence/fedora.rb
- lib/valkyrie/persistence/fedora/metadata_adapter.rb
- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/metadata_adapter.rb
- lib/valkyrie/persistence/memory/persister.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/metadata_adapter.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/metadata_adapter.rb
- lib/valkyrie/persistence/solr/queries/find_members_query.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/queries.rb
- lib/valkyrie/specs/shared_specs/resource.rb
- lib/valkyrie/storage/fedora.rb
- lib/valkyrie/types.rb
- lib/valkyrie/version.rb
- spec/spec_helper.rb
- spec/valkyrie/id_spec.rb
- spec/valkyrie/persistence/fedora/metadata_adapter_spec.rb
- spec/valkyrie/persistence/fedora/permissive_schema_spec.rb
- spec/valkyrie/persistence/memory/metadata_adapter_spec.rb
- spec/valkyrie/persistence/postgres/metadata_adapter_spec.rb
- spec/valkyrie/persistence/solr/metadata_adapter_spec.rb
- spec/valkyrie/persistence/solr/query_service_spec.rb
- spec/valkyrie/types_spec.rb
- valkyrie.gemspec
Reverts samvera-labs/valkyrie#628
We'll do work for 2.0.0 in the `2-0-rc` branch.
> Revert "2.0.0 RC1"

- Gemfile
- README.md
- lib/valkyrie/persistence/postgres.rb
- spec/spec_helper.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
- valkyrie.gemspec
> Removes pg from gemspec to make it an optional dependency

- lib/valkyrie/persistence/postgres.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
> Remove deprecation of pg dependency

- lib/valkyrie/persistence/postgres/persister.rb
- lib/valkyrie/specs/shared_specs/persister.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
This will throw an exception in 2.0.0
Closes #652
> Provide a warning when a PG ID is overridden.

- lib/valkyrie/persistence/postgres/persister.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
for 2.0 release
actually closes #652
> Change deprecation to exception in postgres persister

- lib/valkyrie/persistence/solr/orm_converter.rb
- spec/valkyrie/persistence/solr/orm_converter_spec.rb
The previous logic was causing a bug in Figgy.
> Fix Solr casting.

- lib/valkyrie/persistence/solr.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
> Deprecate RSolr not being defined in Gemfile

- lib/valkyrie.rb
- spec/spec_helper.rb
- spec/valkyrie_spec.rb
- tasks/docker.rake
We were halfway there anyways, just took a couple fixes.
> Remove rails require

- Gemfile
- README.md
- lib/valkyrie/persistence/solr.rb
- spec/valkyrie/persistence/solr/persister_spec.rb
- valkyrie.gemspec
> Remove RSolr dependency.

- Gemfile
- gemfiles/activerecord_5_1.gemfile
- gemfiles/activerecord_5_2.gemfile
- lib/valkyrie/persistence/postgres.rb
- spec/valkyrie/persistence/postgres/persister_spec.rb
- valkyrie.gemspec
> Make activerecord optional.

- lib/valkyrie/resource.rb
- spec/valkyrie/resource_spec.rb
> Don't allow overriding reserved types.

- lib/valkyrie/version.rb
Includes removing one bad require.
> Release 2.0.0 RC5

- lib/valkyrie/resource.rb
- lib/valkyrie/specs/shared_specs/resource.rb
- lib/valkyrie/types.rb
- spec/valkyrie/generators/valkyrie/resource_generator_spec.rb
Significantly speeds up converting to/from `Valkyrie::Resource`
> Dont force optional default

- lib/valkyrie/persistence/shared/json_value_mapper.rb
- lib/valkyrie/specs/shared_specs/persister.rb
> Don't convert non-ISO8601 strings to DateTimes

- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- valkyrie.gemspec
> Remove strftime from Fedora::Persister::ModelConverter

- .docker-stack/valkyrie-development/docker-compose.yml
- .docker-stack/valkyrie-test/docker-compose.yml
- tasks/dev.rake
> Test against Fedora 5.1

- lib/valkyrie/persistence/memory/query_service.rb
> Adding documentation about what alternate identifiers are

- solr/config/solrconfig.xml
> Fixes #766 - Remove suggest component in example Solr Configuration

- db/seeds.rb
Fixes #774 
Removes the unused db seeds file from the code base.
> Remove unused db seeds file.

- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/specs/shared_specs/queries.rb
Co-authored-by: LaRita Robinson @laritakr
Fixes Issue #775 
* updates shared specs to test the model parameter
* implements filter by model for the in memory adapter
* implement filter by model for postgres adapter
* implement filter by model for fedora adapter
> add model parameter on find_inverse_references_by and find_references_by

- README.md
> Use svn instead of png for version badge

- lib/valkyrie/id.rb
- valkyrie.gemspec
No reason to force apps to upgrade Faraday.
> Use a softer Faraday lock

- .circleci/config.yml
- spec/valkyrie/types_spec.rb
> Adding Ruby 2.7 support

- lib/valkyrie/specs/shared_specs/change_set.rb
> Fix shared ChangeSet spec.

- lib/valkyrie/id.rb
- lib/valkyrie/types.rb
- spec/valkyrie/types_spec.rb
> Make ID <=> String equality symmetrical

- .circleci/config.yml
- .rubocop.yml
- Rakefile
- lib/generators/valkyrie/resource_generator.rb
- lib/valkyrie.rb
- lib/valkyrie/change_set.rb
- lib/valkyrie/id.rb
- lib/valkyrie/indexers/access_controls_indexer.rb
- lib/valkyrie/persistence/fedora/list_node.rb
- lib/valkyrie/persistence/fedora/ordered_list.rb
- lib/valkyrie/persistence/fedora/ordered_reader.rb
- lib/valkyrie/persistence/fedora/permissive_schema.rb
- lib/valkyrie/persistence/fedora/persister.rb
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/fedora/query_service.rb
- lib/valkyrie/persistence/memory/persister.rb
- lib/valkyrie/persistence/memory/query_service.rb
- lib/valkyrie/persistence/postgres/orm/resource.rb
- lib/valkyrie/persistence/postgres/orm_converter.rb
- lib/valkyrie/persistence/postgres/query_service.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/queries/find_members_query.rb
- lib/valkyrie/persistence/solr/query_service.rb
- lib/valkyrie/storage/fedora.rb
- lib/valkyrie/storage_adapter.rb
> Remove Outdated TargetVersion from Rubocop Config

- CHANGELOG.md
- lib/valkyrie/persistence/fedora/persister/model_converter.rb
- lib/valkyrie/persistence/solr/model_converter.rb
- lib/valkyrie/persistence/solr/orm_converter.rb
- lib/valkyrie/resource/access_controls.rb
> Replace all references of "master" with "main"

- .circleci/config.yml
- .lando.yml
- README.md
Updating to `6.0.0` instead of `6.0.0-RC-2`
> Use Fedora 6.0.0 release

- valkyrie.gemspec
> gemspec: require 2FA

- README.md
> readme: add min ruby version to dev section

- README.md
> readme: add note about the list of apps and implementations

- lib/valkyrie/persistence/postgres/query_service.rb
> Use find_each

- CHANGELOG.md
- lib/valkyrie/version.rb
> Release v3.1.0

- lib/valkyrie/storage_adapter.rb
Sorry, this amends #952.  Thanks!
> Fixed Valkyrie::StorageAdapter::File#valid? param documentation

- lib/valkyrie/specs/shared_specs/file.rb
- lib/valkyrie/storage_adapter.rb
- spec/valkyrie/storage_adapter/stream_file_spec.rb
> Add cleanup functionality to #disk_path

- CHANGELOG.md
- lib/valkyrie/version.rb
This is a minor version update because it changes shared specs.
> Release version 3.2.0
